---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_2cb2ff82cbd8
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DATABASE_URI
              value: jdbc:mysql://mysqldb:3306/linknamu
            - name: DATABASE_PASSWORD
              value: linknamu12!
            - name: AES_SECRET_KEY
              value: 9a8f7e6d5c4b3a291b0c9d8e7f6a5b4c
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
