---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 여러분의 backend image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_0b544fa607f3
          env:
            - name: TZ
              value: Asia/Seoul
              
            - name: DATABASE_URI
              value: jdbc:mysql://mysqldb:3306/linknamu
              
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
              
            - name: AES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: AES_SECRET_KEY
                  
          resources:
            requests:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
